[project]
name = "daiv"
version = "0.1.0"
description = "AI-driven tool to enhance development productivity by automating routine tasks."
readme = "README.md"
license = {file = "LICENSE"}
maintainers = [
  {name = "Sandro Rodrigues", email = "srtabs@gmail.com"},
]
authors = [
  {name = "Sandro Rodrigues", email = "srtabs@gmail.com"},
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "celery[redis]==5.4",
  "chromadb==0.5.3",
  "django==5.1",
  "django-allauth==64.1",
  "django-appconf==1.0.6",
  "django-celery-beat==2.7",
  "django-csp==3.8",
  "django-extensions==3.2.3",
  "django-ninja==1.3",
  "django-split-settings==1.3.2",
  "django-webpack-loader==3.1",
  "esprima==4.0.1",
  "get-docker-secret==2",
  "instructor==1.4",
  "ipython==8.26",
  "langchain==0.2.15",
  "langchain-chroma==0.1.3",
  "langchain-community==0.2.14",
  "langchain-openai==0.1.23",
  "langchain-text-splitters==0.2.2",
  "litellm==1.44.8",
  "openai==1.42",
  "psycopg[binary]==3.2.1",
  "pydantic==2.8.2",
  "python-decouple==3.8",
  "python-gitlab==4.10",
  "redis==4.6",
  "sentence-transformers==3.0.1",
  "tantivy==0.22",
  "tree-sitter==0.21.3",
  "tree-sitter-languages==1.10.2",
  "unidiff==0.7.5",
  "uvicorn==0.30.6",
]

[tool.ruff]
line-length = 120
target-version = "py312"
force-exclude = true
preview = true
show-fixes = true
extend-exclude = ["*/static/*", "*/node_modules/*"]

[tool.ruff.lint]
ignore = ["N812", "S101"]
select = [
  # flake8-builtins
  "A",
  # flake8-bugbear
  "B",
  # flake8-comprehensions
  "C4",
  # flake8-django
  "DJ",
  # pycodestyle
  "E",
  # eradicate
  "ERA",
  # Pyflakes
  "F",
  # flake8-logging-format
  "G",
  # isort
  "I",
  # flake8-logging
  "LOG",
  # pep8-naming
  "N",
  # flake8-use-pathlib
  "PTH",
  # flake8-bandit
  "S",
  # flake8-simplify
  "SIM",
  # flake8-print
  "T20",
  # flake8-type-checking
  "TCH",
  # pyupgrade
  "UP",
  # pycodestyle
  "W",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
section-order = [
  "future",
  "standard-library",
  "django",
  "third-party",
  "first-party",
  "local-folder",
]
known-first-party = [
  "accounts",
  "automation",
  "codebase",
]

[tool.ruff.lint.isort.sections]
"django" = ["django"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true

  [[tool.mypy.overrides]]
  module = [
    "celery.*",
    "decouple.*",
    "django.*",
    "django_extensions.*",
    "litellm.*",
    "transformers.*",
    "unidiff.*",
    "redis.*",
  ]
  ignore_missing_imports = true

[tool.uv]
dev-dependencies = [
  "coverage==7.6.1",
  "mypy==1.11.2",
  "pre-commit==3.8.0",
  "pyproject-fmt==1.7.0",
  "pyopenssl==24.2.1",
  "ruff==0.6.2",
]
